version: '3.8' 
services:
  app:
    build: .
    environment:
      - SAM_CLI_CONTAINER_CONNECTION_TIMEOUT=60
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:${PWD}:ro
    working_dir: $PWD
    command: "sam local start-api -p 8000 --host 0.0.0.0 --container-host=host.docker.internal --container-host-interface=127.0.0.1 --debug"
    ports:
      - "8000:8000"
    networks:
      - "backend"
networks:
  backend:
    name: aws_backend
    driver: bridge
