AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test Api Gateway
Resources:
  ApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: 'any'

